### ISSUE TITLE
Container doesn't use host system time zone

### ISSUE THREAD

**Issue by sarkonovich** [jpeffer/docker-alexa-hue#1]
The container appears to use the underlying base system default (UTC) instead of the time zone on the host. This leads to the timers/alarms on Alexa Hue to malfunction. For example, if you're at UTC -4, then setting an alarm in an hour will appear to Alexa Hue to be trying to set it in the past.

For now, a work around is to launch the container with the following (example) parameter:

-e "TZ=America/Los_Angeles"

So:

docker run -e "TZ=America/Los_Angeles" -itdP --name=docker-alexa-hue jpeffer/docker-alexa-hue

But the container optimally should sync time zone to host.

**Comment by jpeffer** [comment]
Interesting. Unfortunately, running a docker machine is going to make retrieving the timezone of the host unlikely. If you're running Docker on a native Ubuntu OS, this can be resolved with the following approach:

`docker run -v /etc/localtime:/etc/localtime:ro`

I don't believe this is going to work in a VM on Windows or OSX. 

Is it possible to simply use UTC?

**Comment by sarkonovich** [comment]
Jonathan,

I looked into this a bit, and came up with:

docker run -e "TZ=America/New_York" -itdP --name=docker-alexa-hue
jpeffer/docker-alexa-hue

where you replace the TZ value with your time zone. I've verified that this
works on Mac and Windows (and I assume Linux, too). So, it's a plausible
work around.

I thought there might be a line that could be added to the Docker file. But
if not, that's fine. Adding the parameter to the docker run command deals
with it.

Maybe better, as you suggest, I go back into the code and peg everything to
UTC.

EDIT:  Looks like the Hue API has deprecated setting schedule with UTC. Schedules have to be set with local time, so the above won't work.

Perhaps call the issue closed?

**Comment by jpeffer** [comment]
Wow, that's mildly infuriating they would deprecate the use of UTC. Fairly common best practice is to simply deal in UTC and then have the interpreting device convert. Using the TZ environment variable will be necessary if/when Docker provides a way to access a host's timezone. Sorry!
