### ISSUE TITLE
Alexa Hue required update

### ISSUE THREAD

**Issue by sarkonovich** [jpeffer/docker-alexa-hue#3]
Alexa-Hue required an update after the latest Bridge upgrade deprecated the method by which Alexa-Hue created a new user. That's now been fixed on the Alexa-Hue side.

Docker still seems to be pulling down the older version of Alexa Hue. Ever after deleting the container an all images (`docker rmi $(docker images -q)`), and pulling down new images from here. 

That older version just flat out doesn't work now.

Do you need to push the most recent version of the repo to your Docker hub?

**Comment by jpeffer** [comment]
I triggered a build to push a new image to dockerhub. Give it a shot and see if that made a difference? If it resolves the issue, we should look into enabling some type of webhook into automatically triggering new builds.

**Comment by sarkonovich** [comment]
Okay, I'll check it out. In the meantime, I set up my own Docker Hub, but
I'd like to stick with yours since a) it's yours and b) it's confusing to
have two different hubs.

But, yes...a webhook would be great. Do you know if  that's possible
without linking your Docker hub to my Git hub?

Steve

**Comment by jpeffer** [comment]
I think I can provide a webhook into my docker hub that you can use. I would have to send it to you privately somehow.

**Comment by jpeffer** [comment]
I have pushed a new docker image tonight, which should self-update your alexa-hue project using a 'git pull' command upon startup. Hopefully this addresses the previous issues you were running into. If not, we will need to explore the webhooks idea.
